name: Render menu.pdf
on: push
jobs:
  render-menu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: requirements.typ
      # Now Typst is installed and packages will be cached!
      - run: typst compile main.typ menu.pdf --font-path fonts
      - uses: actions/upload-artifact@v4
        with:
          name: menu
          path: menu.pdf
